name: Test Build

on:
  workflow_dispatch:

jobs:
  check_wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

  build:
    name: Build app
    needs: check_wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build app
        run: ./gradlew detekt assembleDevDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TachiyomiSY-${{ github.sha }}
          path: app/build/outputs/apk/dev/debug/*.apk
